/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/gabriela/open-2015/autobotz_ws/src/rosserial/rosserial_arduino/msg/ultrassom.msg
 *
 */


#ifndef ROSSERIAL_ARDUINO_MESSAGE_ULTRASSOM_H
#define ROSSERIAL_ARDUINO_MESSAGE_ULTRASSOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosserial_arduino
{
template <class ContainerAllocator>
struct ultrassom_
{
  typedef ultrassom_<ContainerAllocator> Type;

  ultrassom_()
    : dir(0.0)
    , esq(0.0)
    , frente(0.0)
    , tras(0.0)  {
    }
  ultrassom_(const ContainerAllocator& _alloc)
    : dir(0.0)
    , esq(0.0)
    , frente(0.0)
    , tras(0.0)  {
    }



   typedef float _dir_type;
  _dir_type dir;

   typedef float _esq_type;
  _esq_type esq;

   typedef float _frente_type;
  _frente_type frente;

   typedef float _tras_type;
  _tras_type tras;




  typedef boost::shared_ptr< ::rosserial_arduino::ultrassom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosserial_arduino::ultrassom_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ultrassom_

typedef ::rosserial_arduino::ultrassom_<std::allocator<void> > ultrassom;

typedef boost::shared_ptr< ::rosserial_arduino::ultrassom > ultrassomPtr;
typedef boost::shared_ptr< ::rosserial_arduino::ultrassom const> ultrassomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosserial_arduino::ultrassom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosserial_arduino::ultrassom_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosserial_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosserial_arduino': ['/home/gabriela/open-2015/autobotz_ws/src/rosserial/rosserial_arduino/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::ultrassom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::ultrassom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::ultrassom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::ultrassom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::ultrassom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::ultrassom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosserial_arduino::ultrassom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb6e69afd8489e9696f90b5f332c934f";
  }

  static const char* value(const ::rosserial_arduino::ultrassom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb6e69afd8489e96ULL;
  static const uint64_t static_value2 = 0x96f90b5f332c934fULL;
};

template<class ContainerAllocator>
struct DataType< ::rosserial_arduino::ultrassom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosserial_arduino/ultrassom";
  }

  static const char* value(const ::rosserial_arduino::ultrassom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosserial_arduino::ultrassom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 dir\n\
float32 esq\n\
float32 frente\n\
float32 tras\n\
";
  }

  static const char* value(const ::rosserial_arduino::ultrassom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosserial_arduino::ultrassom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dir);
      stream.next(m.esq);
      stream.next(m.frente);
      stream.next(m.tras);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ultrassom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosserial_arduino::ultrassom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosserial_arduino::ultrassom_<ContainerAllocator>& v)
  {
    s << indent << "dir: ";
    Printer<float>::stream(s, indent + "  ", v.dir);
    s << indent << "esq: ";
    Printer<float>::stream(s, indent + "  ", v.esq);
    s << indent << "frente: ";
    Printer<float>::stream(s, indent + "  ", v.frente);
    s << indent << "tras: ";
    Printer<float>::stream(s, indent + "  ", v.tras);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSERIAL_ARDUINO_MESSAGE_ULTRASSOM_H
