/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/gabriela/open-2015/autobotz_ws/src/estrategia/msg/velocidade.msg
 *
 */


#ifndef ESTRATEGIA_MESSAGE_VELOCIDADE_H
#define ESTRATEGIA_MESSAGE_VELOCIDADE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace estrategia
{
template <class ContainerAllocator>
struct velocidade_
{
  typedef velocidade_<ContainerAllocator> Type;

  velocidade_()
    : linear()
    , angular()  {
    }
  velocidade_(const ContainerAllocator& _alloc)
    : linear(_alloc)
    , angular(_alloc)  {
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _linear_type;
  _linear_type linear;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _angular_type;
  _angular_type angular;




  typedef boost::shared_ptr< ::estrategia::velocidade_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::estrategia::velocidade_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct velocidade_

typedef ::estrategia::velocidade_<std::allocator<void> > velocidade;

typedef boost::shared_ptr< ::estrategia::velocidade > velocidadePtr;
typedef boost::shared_ptr< ::estrategia::velocidade const> velocidadeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::estrategia::velocidade_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::estrategia::velocidade_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace estrategia

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'estrategia': ['/home/gabriela/open-2015/autobotz_ws/src/estrategia/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::estrategia::velocidade_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::estrategia::velocidade_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::estrategia::velocidade_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::estrategia::velocidade_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::estrategia::velocidade_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::estrategia::velocidade_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::estrategia::velocidade_<ContainerAllocator> >
{
  static const char* value()
  {
    return "624d0bd1a9116896d149b60f7e32ef01";
  }

  static const char* value(const ::estrategia::velocidade_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x624d0bd1a9116896ULL;
  static const uint64_t static_value2 = 0xd149b60f7e32ef01ULL;
};

template<class ContainerAllocator>
struct DataType< ::estrategia::velocidade_<ContainerAllocator> >
{
  static const char* value()
  {
    return "estrategia/velocidade";
  }

  static const char* value(const ::estrategia::velocidade_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::estrategia::velocidade_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 linear\n\
std_msgs/Float32 angular\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::estrategia::velocidade_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::estrategia::velocidade_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct velocidade_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::estrategia::velocidade_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::estrategia::velocidade_<ContainerAllocator>& v)
  {
    s << indent << "linear: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESTRATEGIA_MESSAGE_VELOCIDADE_H
